# Generated by Django 4.1.2 on 2022-10-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zapisy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specjalizacja', models.CharField(max_length=60)),
                ('Nazwa_lekarza', models.CharField(max_length=60)),
            ],
        ),
    ]
