# Generated by Django 4.1.2 on 2022-10-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specjalizacje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Specjalizacja',
                'verbose_name_plural': 'Specjalizacje',
            },
        ),
        migrations.AlterModelOptions(
            name='zapisy',
            options={'verbose_name': 'Zapisy', 'verbose_name_plural': 'Zapisy'},
        ),
    ]
