# Generated by Django 4.1.2 on 2022-10-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0002_specjalizacje_alter_zapisy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Lekarz',
                'verbose_name_plural': 'Lekarze',
            },
        ),
    ]
