# Generated by Django 4.1.2 on 2022-10-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0003_lekarze'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekarze',
            name='specjalizacja',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
