# Generated by Django 4.1.2 on 2022-10-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0005_rename_nazwa_lekarza_zapisy_imie_pacjenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapisy',
            name='Wybor_z_listy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Zapisy.specjalizacje'),
        ),
    ]
