# Generated by Django 4.1.2 on 2022-10-14 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0006_zapisy_wybor_z_listy'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapisy',
            name='Wybor_lekarza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Zapisy.lekarze'),
        ),
    ]
