# Generated by Django 4.1.2 on 2022-10-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0007_zapisy_wybor_lekarza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lekarze',
            old_name='imie',
            new_name='nazwa',
        ),
        migrations.RemoveField(
            model_name='lekarze',
            name='nazwisko',
        ),
        migrations.RemoveField(
            model_name='lekarze',
            name='specjalizacja',
        ),
        migrations.RemoveField(
            model_name='zapisy',
            name='Wybor_z_listy',
        ),
    ]
