# Generated by Django 4.1.2 on 2022-10-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0008_rename_imie_lekarze_nazwa_remove_lekarze_nazwisko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapisy',
            name='Czas',
            field=models.TimeField(null=True),
        ),
    ]
