# Generated by Django 4.1.2 on 2022-10-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0009_zapisy_czas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapisy',
            name='Czas',
            field=models.DateTimeField(null=True),
        ),
    ]
