# Generated by Django 4.1.2 on 2022-10-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0010_alter_zapisy_czas'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekarze',
            name='specjalizacja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Zapisy.specjalizacje'),
        ),
    ]
