# Generated by Django 4.1.2 on 2022-10-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0012_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
        migrations.AddField(
            model_name='product',
            name='Czas',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Imie_pacjent',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Nazwisko_pacjent',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Wybor_lekarza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Zapisy.lekarze'),
        ),
    ]
