# Generated by Django 4.1.2 on 2022-10-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0013_alter_product_options_product_czas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10000),
        ),
    ]
