# Generated by Django 4.1.2 on 2022-10-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0014_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descripton',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
