# Generated by Django 4.1.2 on 2022-10-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0015_remove_product_descripton_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Zapisy_Pacjent',
        ),
        migrations.AlterModelOptions(
            name='zapisy_pacjent',
            options={'verbose_name': 'Zapisy_Pacjent', 'verbose_name_plural': 'Zapisy_Pacjent'},
        ),
    ]
