# Generated by Django 4.1.2 on 2022-10-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0016_rename_product_zapisy_pacjent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lekarze',
            options={'verbose_name': 'Zapisy', 'verbose_name_plural': 'Zapisy'},
        ),
        migrations.DeleteModel(
            name='Zapisy',
        ),
    ]
