# Generated by Django 4.1.2 on 2022-10-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0018_alter_lekarze_options_zapisy_pacjent_specjalizacja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapisy_pacjent',
            name='specjalizacja',
        ),
    ]
