# Generated by Django 4.1.2 on 2022-10-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0021_pogoda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formularz_kontaktowy',
            options={'verbose_name': 'Formularz_kontaktowy', 'verbose_name_plural': 'Formularz_kontaktowy'},
        ),
        migrations.AddField(
            model_name='zapisy_pacjent',
            name='Data',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
