# Generated by Django 4.1.2 on 2022-10-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0023_aktualnosci_delete_pogoda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapisy_pacjent',
            name='Czas',
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='informacja',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='zapisy_pacjent',
            name='Data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
