# Generated by Django 4.1.2 on 2022-10-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0024_remove_zapisy_pacjent_czas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejestracja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=60)),
                ('password', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
