# Generated by Django 4.1.2 on 2022-10-22 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0025_rejestracja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rejestracja',
        ),
    ]
