# Generated by Django 4.1.2 on 2022-11-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0026_delete_rejestracja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aktualnosci',
        ),
    ]
