# Generated by Django 4.1.3 on 2022-12-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0027_delete_aktualnosci'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapisy_pacjent',
            name='Czas',
            field=models.TimeField(null=True),
        ),
    ]
