# Generated by Django 4.1.3 on 2022-12-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0028_zapisy_pacjent_czas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapisy_pacjent',
            name='Data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
