# Generated by Django 4.1.3 on 2022-12-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0034_alter_zapisy_pacjent_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oceny_Lekarzy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ocena', models.CharField(max_length=10, null=True)),
                ('Wybor_lekarza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Zapisy.lekarze')),
            ],
        ),
    ]
