# Generated by Django 4.1.3 on 2022-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisy', '0035_oceny_lekarzy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oceny_lekarzy',
            options={'verbose_name': 'Oceny', 'verbose_name_plural': 'Oceny'},
        ),
        migrations.AlterField(
            model_name='oceny_lekarzy',
            name='Ocena',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
